diff: true
extension: 
  - js
opts: false
recursive: true
require: 
  - "./mocha-helper.cjs"
reporter: spec
slow: 75
sort: false
timeout: 2000
ui: bdd
spec: "src/**/*.spec.js"
watch-files: 
  - "src/**/*.js"
