name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    # Drafts your next Release notes as Pull Requests are merged into "master"
    steps:
      - uses: release-drafter/release-drafter@v5
